http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
  
postgres:
  host: "localhost"
  port: "5432"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days