basePath: /api/v1
definitions:
  domain.MemberCreate:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      membership_id:
        type: integer
      phone_number:
        type: string
    required:
    - first_name
    - last_name
    - membership_id
    - phone_number
    type: object
  domain.MemberUpdate:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
    type: object
  domain.RefreshInput:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  domain.SignInInput:
    properties:
      password:
        type: string
      phone_number:
        type: string
    required:
    - password
    - phone_number
    type: object
  service.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  v1.dataResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  v1.response:
    properties:
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: REST API for Gym Management
  title: Gym Manager API
  version: "1.0"
paths:
  /managers/auth/refresh:
    post:
      consumes:
      - application/json
      description: manager refresh
      parameters:
      - description: refresh info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Manager Refresh Tokens
      tags:
      - manager-auth
  /managers/manager/create:
    post:
      description: manager creation
      responses: {}
      security:
      - ManagerAuth: []
      summary: Create New Manager
      tags:
      - manager
  /managers/members/create:
    post:
      consumes:
      - application/json
      description: member creation
      parameters:
      - description: member info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.MemberCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - ManagerAuth: []
      summary: Create Member
      tags:
      - members
  /managers/members/delete/{id}:
    delete:
      description: delete member by id
      parameters:
      - description: Member ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - ManagerAuth: []
      summary: Delete Member By ID
      tags:
      - members
  /managers/members/get/{id}:
    get:
      description: get member by id
      parameters:
      - description: Member ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.dataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - ManagerAuth: []
      summary: Get Member By ID
      tags:
      - members
  /managers/members/update/{id}:
    put:
      consumes:
      - application/json
      description: update member by id with json body
      parameters:
      - description: Member ID
        in: path
        name: id
        required: true
        type: integer
      - description: member update info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.MemberUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      security:
      - ManagerAuth: []
      summary: Update Member By ID
      tags:
      - members
  /managers/sign-in:
    post:
      consumes:
      - application/json
      description: manager sign in
      parameters:
      - description: sign up info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Manager Sign In
      tags:
      - manager-auth
securityDefinitions:
  ManagerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
